# Generated by Django 3.0.2 on 2020-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productImageLink', models.URLField()),
                ('productLink', models.URLField()),
            ],
        ),
    ]
