# Generated by Django 3.0.2 on 2020-11-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_contact_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='consent',
            field=models.BooleanField(default=True),
        ),
    ]
