# Generated by Django 3.0.2 on 2020-11-12 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(max_length=50)),
                ('myDate', models.DateField()),
                ('myLocation', models.CharField(max_length=50)),
                ('myDuration', models.IntegerField(max_length=4)),
                ('myDescription', models.CharField(max_length=1000)),
                ('myCapacity', models.IntegerField(max_length=4)),
                ('myCost', models.FloatField(max_length=6)),
                ('myBooked', models.IntegerField(max_length=4)),
                ('myCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
