# Generated by Django 3.0.2 on 2020-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='myBooked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mycalendar',
            name='myCapacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mycalendar',
            name='myDuration',
            field=models.IntegerField(),
        ),
    ]
