# Generated by Django 3.1.3 on 2020-11-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0002_auto_20201112_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventDate', models.DateField()),
                ('eventLocation', models.CharField(max_length=50)),
                ('eventDuration', models.IntegerField()),
                ('eventDescription', models.CharField(max_length=1000)),
                ('eventCapacity', models.IntegerField()),
                ('eventCost', models.FloatField(max_length=6)),
                ('eventBooked', models.IntegerField()),
                ('eventCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='myCalendar',
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='bookingEventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.event'),
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='bookingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
