# Generated by Django 3.1.3 on 2020-11-18 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_auto_20201118_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventDuration',
        ),
        migrations.AddField(
            model_name='event',
            name='eventEnd',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventStart',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
