# Generated by Django 3.1.3 on 2020-11-25 14:24

import Accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0004_auto_20201118_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventBooked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventCreator',
            field=models.ForeignKey(default=Accounts.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
