# Generated by Django 3.1.3 on 2020-11-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0009_auto_20201125_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='bookingUser',
            field=models.ForeignKey(default='Accounts.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventCreator',
            field=models.ForeignKey(default='Accounts.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
